// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCkAWweo0ndSrxVIhTodOvPUkogGFqpgQw',
    appId: '1:765781157278:web:7b87a53174042c7408628f',
    messagingSenderId: '765781157278',
    projectId: 'login-cb37c',
    authDomain: 'login-cb37c.firebaseapp.com',
    storageBucket: 'login-cb37c.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCkYq8XxhKA98QPR43x01CqnmwqNVuzuX4',
    appId: '1:765781157278:android:d9b111234544d80808628f',
    messagingSenderId: '765781157278',
    projectId: 'login-cb37c',
    storageBucket: 'login-cb37c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDh_HqjYd3ApBAbpAd2qw5W4ww3sAqrh_4',
    appId: '1:765781157278:ios:340df0e83a97eb3808628f',
    messagingSenderId: '765781157278',
    projectId: 'login-cb37c',
    storageBucket: 'login-cb37c.appspot.com',
    iosClientId: '765781157278-mi0haao5m5qmofdflfb7i2c0g58bsujl.apps.googleusercontent.com',
    iosBundleId: 'com.example.loginFirebase',
  );
}
